# Generated by Django 3.0.3 on 2021-08-06 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin', models.CharField(max_length=100)),
                ('Room_Name', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Balance', models.BigIntegerField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mem_Name', models.CharField(max_length=100)),
                ('PayId', models.CharField(max_length=100)),
                ('Balance', models.BigIntegerField(default=5000)),
                ('RoomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Rooms')),
            ],
        ),
    ]
